services:
  ym-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: component_library
    ports:
      - '5015:5000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
